name: Validate CSV gene lists

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv pip install -e .

    - name: Validate CSV files
      id: validate_csv
      run: |
        source .venv/bin/activate
        python src/genlister/validate.py cnv cnv/moma/gener.csv > validation_output.txt

    - name: Check if validation output is not empty
      id: check_files
      run: |
        if [ -s validation_output.txt ]; then
          echo "has_content=true" >> $GITHUB_OUTPUT
          # echo "::set-output name=has_content::true"
        else
          echo "has_content=false" >> $GITHUB_OUTPUT
          # echo "::set-output name=has_content::false"
        fi

    - name: PR comment with file
      if: steps.check_files.outputs.has_content == 'true'
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: validation_output.txt
